### ISSUE TITLE
unsaved changes warning not working

### ISSUE THREAD

**Issue by iskar-jarak** [glyphr-studio/Glyphr-Studio-2#121]
**Describe the bug**
When closing Glyphr Studio 2 window it does not warn of unsaved changes even if the box is checked 

**To Reproduce**
1. Go to Settings and check if 'warn about unsaved changes on window close' box is ticked 
2. Close window - no warning will appear 

**Expected behavior**
Expected to have a popup warning when closing window (like v1)

**Comment by mattlag** [comment]
This was fixed in v2 Beta 2.0, out now at [www.glyphrstudio.com/v2/app](http://www.glyphrstudio.com/v2/app)
