### ISSUE TITLE
Save font size and line gap when leaving "live preview"

### ISSUE THREAD

**Issue by ecstrema** [glyphr-studio/Glyphr-Studio-2#122]
## Problem 

I need on a font that reads comfortably from around 120 px. (It's not a text font). When I go to live preview, I always need to make the glyph size larger, since it always reset to 48px.

## Solution
Save the last font size (and line height) when leaving the "live preview", so it can be restored when coming back, the same way the text is saved.

## Reproduction
Here's the bug. The font size is not restored

https://github.com/glyphr-studio/Glyphr-Studio-2/assets/35939574/9ccaf86e-6dc6-49e9-b14c-54be2fcb0d17

**Comment by ecstrema** [comment]
Forgot to say how awesome this project is. Keep up the good work!

**Comment by mattlag** [comment]
Thank you! This was fixed in v2 Beta 2.0, out now at www.glyphrstudio.com/v2/app
