### ISSUE TITLE
List of character ranges does not scroll

### ISSUE THREAD

**Issue by JapanYoshi** [glyphr-studio/Glyphr-Studio-2#144]
**Describe the bug & what the expected behavior should be:**

When opening a font with wide Unicode coverage, the list of character ranges in the overview screen extends out of the screen. It stays fixed in the window and cannot be scrolled with the mouse wheel or arrow keys, rendering the later ranges inaccessble without zooming out an obscene amount.

**Steps to reproduce the bug:**

1. Load a font with wide Unicode coverage

2. Show list of character ranges from the dropdown list

**Other notes & screenshots:**

![image](https://github.com/glyphr-studio/Glyphr-Studio-2/assets/8707990/f0bb0f44-39ae-406b-ad71-435c27c2f9d9)

**Comment by mattlag** [comment]
Good catch - I'll get this fixed.  Thanks for filing the bug!

**Comment by mattlag** [comment]
Fixed in v2.0.0
