### ISSUE TITLE
SVG Export: Characters are not escaped properly

### ISSUE THREAD

**Issue by ThePaSch** [glyphr-studio/Glyphr-Studio-2#153]
**Describe the bug & what the expected behavior should be:**
When exporting to SVG, certain characters are not escaped properly in `<glyph>` elements' `unicode` properties, leading to parse errors when trying to open the exported SVG in any software. For example, a `"` glyph will be exported as `<glyph glyph-name="Quotation_mark" unicode=""" />`, or a `<` glyph as `<glyph glyph-name="Less-than_sign" unicode="<" />`; neither are valid SVG and will fail to open in any SVG editor.

The SVG export routine should escape sensitive characters that are part of the SVG syntax; for instance, `"` should be escaped as `&quot;`, and `<` as `&lt;`.

**Steps to reproduce the bug:**

1. Export any font that provide glyphs for protected SVG characters as SVG.
2. Open the resulting SVG in any text editor; the protected characters are not escaped.

**Comment by mattlag** [comment]
Confirmed - this is a bug, thank you for filing it!

**Comment by mattlag** [comment]
This was just fixed in 2.0.1!
