### ISSUE TITLE
Create tofu/notdef glyph

### ISSUE THREAD

**Issue by rayzchen** [glyphr-studio/Glyphr-Studio-2#156]
**Describe the new feature and what scenario it helps support:**

Since Glyphr only supports the Basic Multilingual Plane, the notdef glyph cannot be accessed (U+10FFEE). I would like to change the notdef glyph for my font.

**Comment by mattlag** [comment]
Hello! A couple of notes:
 - The glyph you mention (U+10FFEE) is not the `notdef` glyph, this is in the "Supplementary Private Use Area B" range.  All the "Private Use" areas have no definitions for code points. Anyone can use them for any purpose.
 - The `notdef` glyph is usually just U+0
 - Glyphr Studio v1 could not edit control characters or things above the BMP - but in Glyphr Studio v2, there is no limit to the ranges and glyphs you can add to your project!
 - If you want to edit U+0, you can enable the "Basic Latin Controls" range by going to Settings > Project > Add Standard Ranges from Unicode. 
 - If you want to edit U+10FFEE, you will have to go to Settings > Project > Add a Custom Character Range

Let me know if you have any questions!
