### ISSUE TITLE
Kerning is not exported.

### ISSUE THREAD

**Issue by matj1** [glyphr-studio/Glyphr-Studio-2#188]
### Describe the bug & what the expected behavior should be:

When I export a font from Glyphr Studio as OTF, the exported font does not have kerning. I expect that it would have the kerning which I set in the editor.

I encountered this with my font in practice, but I created an example font where it can be easily seen (further called “the kerning test”).

### Steps to reproduce the bug:

1. Get [the kerning test](https://github.com/glyphr-studio/Glyphr-Studio-2/files/14111187/kerning.test.gs2.json), remove “.json” from the end of the name, and open it in Glyphr Studio.
2. Check that the pair AB has noticeable kerning set.
3. Export it as OTF.
4. Display “AB” in the exported font.
5. Check that the kerning is not there.

### Other notes & screenshots:

In the editor:

![“AB” in the kerning test in the editor](https://github.com/glyphr-studio/Glyphr-Studio-2/assets/22873928/0dc6bbcb-a1b6-4a66-b291-a4b889797023)

In LibreOffice Writer:

![“AB” in the kerning test in LibreOffice Writer](https://github.com/glyphr-studio/Glyphr-Studio-2/assets/22873928/42cc1877-8e40-4fd3-b38e-fa75bcd1668a)

**Comment by mattlag** [comment]
Unfortunately, Kern information cannot be exported directly to OTF (It's a limitation of opentype.js the library we use to write OTF files).

The work around is to export to SVG instead, then use an online font converter to convert to OTF.

https://www.glyphrstudio.com/help/getting-started/import-export.html

**Comment by matj1** [comment]
I thank you for the information. I finished the font in FontForge. I was avoiding FontForge previously because it was too buggy.

**Comment by mkacct** [comment]
@mattlag

> The work around is to export to SVG instead, then use an online font converter to convert to OTF.

I've just encountered this issue; could you recommend such an online font converter? I haven't been able to find one that works correctly and preserves kerning data.

**Comment by mattlag** [comment]
Hi @mkacct 
As it turns out, the latest version (v2.5.0) was just released today, and it supports exporting kern data directly to OTF files. So this extra step (export to SVG then convert) should no longer be required.

**Comment by mkacct** [comment]
@mattlag Oh, thank you very much!
