### ISSUE TITLE
I can't delete any kern group in the editor.

### ISSUE THREAD

**Issue by matj1** [glyphr-studio/Glyphr-Studio-2#189]
### Describe the bug & what the expected behavior should be:

When I try to delete a kern group by clicking the red cross with “Delete this kern group” on the page Kerning, nothing happens. I expect that the group would be deleted.

### Steps to reproduce the bug:

1. Create a kern group in a Glyphr Studio project.
2. With that group shown in the editor, click the red cross with “Delete this kern group”.
3. Check that the group is not deleted.

### Other notes & screenshots:

The only way which I know to remove a kern group in a Glyphr Studio project is to save the project, open it in a text editor, delete the kern group there, and reload the project in the editor.

**Comment by mattlag** [comment]
This was a simple bug, and I fixed it in the source. The fix will go out with the next release. Thank you!

**Comment by mattlag** [comment]
The fix was just shipped in v2.1.4
