### ISSUE TITLE
Ligatures don't work properly when exported

### ISSUE THREAD

**Issue by SzalaiMate25** [glyphr-studio/Glyphr-Studio-2#199]
I'm trying to make an abugida font, and as soon as exported the font I noticed that ligatures don't work properly. Most of the time they don't work at all, but sometimes the wrong glyph is made.

![ligatures dont work properly](https://github.com/glyphr-studio/Glyphr-Studio-1/assets/157370645/14b266c6-2444-4ace-b192-d051dd2acf18)

Here is [my project file](https://file.io/7OUxsty7CPbX) and [my .otf file](https://file.io/eeqHzZSatbTm)

**Comment by mattlag** [comment]
I did a quick investigation here. Unfortunately, it seems like a program specific thing, and how they handle ligatures. I installed your font, then tried to do the sample texts (`thai` `shoi` `khae`) 

in Microsoft Word (fail):
![image](https://github.com/glyphr-studio/Glyphr-Studio-2/assets/5897669/343cce92-762f-4b15-af04-c33c96add952)


Then again in Adobe Illustrator, and it worked perfectly:
![image](https://github.com/glyphr-studio/Glyphr-Studio-2/assets/5897669/06ccb50b-a2c3-4055-b9ae-9fe093e7d2d4)


Ligatures are definitely an advanced feature, and unfortunately, they get handled very differently across apps. Also, from the Glyphr Studio side, I'm not sure how we could 'fix' this issue. We don't have many options for how we export Ligatures (we use OpenType.js to handle reading and writing font files).

What app are you trying to use?

**Comment by mattlag** [comment]
I realized Word was automatically capitalizing things. With a few random tweaks I was able to get it looking 'correct'. But it still wasn't as smooth as just regularly typing out characters and having the ligatures just work.

![image](https://github.com/glyphr-studio/Glyphr-Studio-2/assets/5897669/d68c08b3-0f19-4236-a9b6-4a39381c1b02)

**Comment by mattlag** [comment]
I'm going to close this as it seems to be the word processor's interpretation of ligatures, as opposed to a bug in Glyphr Studio.
