### ISSUE TITLE
Online Glyphr editor's otf font importer does not work

### ISSUE THREAD

**Issue by valeriodiste** [glyphr-studio/Glyphr-Studio-2#205]
**Bug description:**
The online Glyphr editor at https://www.glyphrstudio.com/app/ does not work (as of version 2.1.9) when trying to import an .otf font (web page is stuck on "Working..." and browser console shows errors).

**Steps to reproduce the bug:**
1. Open https://www.glyphrstudio.com/app/ and move to the "Load" tab to import an .otf file
2. Select an .otf file (tested with the OTF font downloaded from https://www.dafont.com/astral-studio.font)
3. Page is now stuck on "Working..." and throws errors in the browser's web console (tested on Chrome).

**Comment by mattlag** [comment]
I just pushed the fix for this about an hour ago - go try it again.

Thank you for letting me know!
