### ISSUE TITLE
Support for WOFF2 format

### ISSUE THREAD

**Issue by 5e-Cleric** [glyphr-studio/Glyphr-Studio-2#216]
I have some fonts in `.woff2` format, that i have since lost the `.otf` version, converting seems to mess with the general kerning, and i would love if apart from `.woff`, `.woff2` could be edited.

I do not know much about the internal differences between the two, so if this is not easily achieved, i can close this issue.

**Comment by mattlag** [comment]
Hello! `woff2` is actually not supported. OpenType.js, the library we use to read and write font files, only supports `woff` - aparently `woff2` uses some compression algorithm that is too big to ship with OpenType.js 

If you want to read more you can see it at the link below. But, in general, if OpenType.js doesn't support it, Glyphr Studio doesn't either.

https://github.com/opentypejs/opentype.js/issues/183#issuecomment-1147228025

**Comment by 5e-Cleric** [comment]
As far as i can read in that issue and the PR that "solved" it, they are leaving the compression step from woff to woff2 and inverse to the end user (AKA Glyphr in this case).

But i understand having other priorities

**Comment by mattlag** [comment]
Yeah, and this type of thing is outside of my area of expertise :-) It is an extra step, but it's pretty easy to use some online font converter to convert to/from woff2 to be able to work on it in other tools.
