### ISSUE TITLE
Attempting to paste SVG into Character Editing panel fails with TypeError on ChromeOS

### ISSUE THREAD

**Issue by jessepav** [glyphr-studio/Glyphr-Studio-2#222]
**Describe the bug & what the expected behavior should be:**

Hitting Ctrl+V to paste SVG text should have Glyphr import that as SVG

**Steps to reproduce the bug:**

1.  Copy SVG text to clipboard

2.  Press Ctrl+V to paste

**Other notes & screenshots:**

Here is the console log for the failed paste

```
index-C3_Ahlmg.js:17868 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Sx (index-C3_Ahlmg.js:17868:3248)
    at HTMLDocument.Gp (index-C3_Ahlmg.js:17778:3547)
```

This is the SVG text I was attempting to paste:

![a](https://github.com/user-attachments/assets/fe020cb3-95ae-482a-aa06-35a9ae2d9241)

**Comment by mattlag** [comment]
I found the bug and fixed it, thank you! Should be released today.

**Comment by mattlag** [comment]
Fixed in v2.4.3

**Comment by jessepav** [comment]
Thank you for the quick fix - works perfectly now.

**Comment by mattlag** [comment]
If you catch me while I'm already fixing bugs, my response time can be quite fast 😄
