### ISSUE TITLE
Can't import a .ttf file

### ISSUE THREAD

**Issue by lucastucious** [glyphr-studio/Glyphr-Studio-2#231]
**Describe the bug & what the expected behavior should be:**
Importing a .ttf file error, see screenshot

**Steps to reproduce the bug:**

Load -> Import .ttf

**Other notes & screenshots:**
![image](https://github.com/user-attachments/assets/8dd119a5-a2fc-4627-8043-9683bfffe5bf)

I can't link the .ttf in github tought

**Comment by mattlag** [comment]
If you could, would you send the .ttf to mail@glyphrstudio.com? I found the code responsible, and this is an extreme edge case that "should never happen"... so I'm very curious how it's happening 😄

**Comment by lucastucious** [comment]
Does this link work ?
https://drive.google.com/file/d/10LNl0X8Rz5wWk7IU1UTDJpy3LxZBgtRD/view?usp=drivesdk

**Comment by mattlag** [comment]
Perfect! I have reproduced the bug, and I'll be able to fix it. Thank you!

**Comment by mattlag** [comment]
Just shipped v2.5.1, this issue is fixed now!
