### ISSUE TITLE
EditCanvas bleeds tool cursors on PanelHandlerFlyoutListSelect

### ISSUE THREAD

**Issue by mechanicious** [glyphr-studio/Glyphr-Studio-2#3]
### Example
Pan Tool cursor bleed

![](https://i.imgur.com/vKYnHjT.png)

**Comment by mattlag** [comment]
The cursor is one issue, but overall I think the Paper Tool needs onMouseOut and onMouseOver event handlers for the EditCanvas.

**Comment by mechanicious** [comment]
This one is fixed, I'll close the issue once I push the commit.

**Comment by mechanicious** [comment]
Setting `document.style.cursor` is not the right way to go.
