### ISSUE TITLE
Clear guide layer on GlyphCanvas save to reduce project export size

### ISSUE THREAD

**Issue by mechanicious** [glyphr-studio/Glyphr-Studio-2#7]

**Comment by mattlag** [comment]
Some guides should be saved at the project level (key metrics like x-height, cap-height, descent, etc)

Per-glyph guides should be saved programmatically, as opposed to saving the Paper.js representation of them.  In V1 they were simple:
* Name
* Color
* Horizontal / Vertical
* Position

**Comment by mechanicious** [comment]
Yeah there will be definitely a dedicated class for the Guides, with bunch of functionality so it will end up having its own storage controller anyways.
