### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-2#8]
Spec out what keyboard shortcuts we'll create for our Beta 1 release.

**Action** | **Shortcut** | **Selection**
:--- | :--- | :---
Cut | `Ctrl`+`X` | Path
Copy | `Ctrl`+`C` | Path
Paste | `Ctrl`+`V` | Path
Delete | `Delete` | Path, PathPoint
Nudge | `⭠` `⭡` `⭢` `⭣` | Path, PathPoint
Save Project | `Ctrl`+`S` | 
Export to OTF | `Ctrl`+`E` | 
Text input mode | `Ctrl`+`T` |

**Comment by mechanicious** [comment]
Moved to [wiki](https://github.com/glyphr-studio/Glyphr-Studio-2/wiki/User-Shortcuts).
